name: Train MLflow Model

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: MLProject/conda.yaml
        activate-environment: titanic_env
        auto-activate-base: false

    - name: Run MLflow Project
      run: |
        cd MLProject
        conda run -n mlflow-env mlflow run . --env-manager=local
